# NumPy

Импортируем библиотеку `numpy`.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
np.random.seed(42)

`as np` - это сокращение, благодаря нему вместо `numpy` достаточно писать `np`.

## Создание массивов и визуализация

Создание обычного list (списка) в языке Python

In [ ]:
arr_python = np.array([
  [1, 2],
  [3, 4],
  [3, 3]
])

In [ ]:
b = [
    [1, 2],
    [2, 3]
]

In [ ]:
arr_python.shape

(3, 2)

In [ ]:
temp + 5

NameError: ignored

In [ ]:
a = [1, 2, 3, 2, 2] # перечисляем элементы
print(a)
print("a.count(2): {}".format(a.count(2)))
a.append(9)
print(a)

[1, 2, 3, 2, 2]
a.count(2): 3
[1, 2, 3, 2, 2, 9]


In [ ]:
type(a) # проверим, что это list

list

Создание массива NumPy с помощью конструктора numpy.array()

In [ ]:
b = np.array([1, 2, 3]) # передаём в конструктор list
print(b)

[1 2 3]


In [ ]:
type(b) # проверим тип

numpy.ndarray

С помощью встроенного свойства `shape` можно узнать размерность массива

In [ ]:
print(b.shape) # проверим размерность

(3,)


Обращение к элементам массива NumPy происходит так же, как и обращение к `list` в Python - квадратные скобки и индекс элемента.

In [ ]:
print(a[0], a[1], a[2])

1 2 3


## Двумерные массивы

Создадим двумерный `list` в Python

In [ ]:
a = [[1, 2, 3], [4, 5, 6]] # перечисление элементов
print(a)

[[1, 2, 3], [4, 5, 6]]


In [ ]:
type(a)

list

Для создания двумерного массива NumPy используем тот же конструктор - `numpy.array()`, в который передаём двумерный `list`.

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
type(b) # проверяем тип

numpy.ndarray

In [ ]:
print(b.shape) # проверяем размерность

(2, 3)


Обращаться к элементам в двумерном массиве можно как обычным, "питоновским" способом (каждый индекс в отдельных скобках)...

In [ ]:
b[0][1] # сначала строки, потом столбцы

2

...так и с помощью одних квадратных скобок (не работает с типом `list`).

In [ ]:
b[0, 1] # сначала строки, потом столбцы

2

Создадим ещё один двумерный массив побольше.

In [ ]:
c = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]])
print(c)
print("c.shape: {}".format(c.shape))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
c.shape: (4, 5)


Чтобы выбрать несколько индексов подряд между двумя значениями, можно использовать формулу `a:b`, где `a` - первое значение, `b` - второе (невключительно).

Формула `:a` означает с первого индекса до `a` (невключительно), формула `a:` означает с элемента `a` до последнего индекса (включительно).

In [ ]:
c[2:4, 2:]

array([[13, 14, 15],
       [18, 19, 20]])

In [ ]:
## Встроенные функции создания матриц

Для создания матрицы, наполненной нулями, используйте метод `numpy.zeros((x, y))`, передав размер в качестве аргумента.

In [ ]:
arr = np.zeros((5, 5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Для создания матрицы, наполненной единицами, используйте метод `numpy.ones((x, y))`, передав размер в качестве аргумента.

In [ ]:
arr = np.ones((6, 4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Для создания матрицы, наполненной одним числом, используйте метод `numpy.full((x, y), n)`, передав размер и число в качестве аргумента.

In [ ]:
arr = np.full((4, 4), 42)
print(arr)

[[42 42 42 42]
 [42 42 42 42]
 [42 42 42 42]
 [42 42 42 42]]


Для создания матрицы с единицами по диагонали и нулями в остальных элементах, используйте `numpy.eye(x)`, передав размер в качестве аргумента. Матрица квадратная, поэтому достаточно одного числа.

Для создания матрицы с единицами по диагонали и нулями в остальных элементах, используйте `numpy.eye(x)`, передав размер в качестве аргумента. Матрица квадратная, поэтому достаточно одного числа.

Для создания матрицы заданного размера, наполненной случайными числами из отрезка `[0, 1)`, используйте метод `numpy.random.random((x, y))`, передав размер в качестве аргумента.

In [ ]:
arr = np.random.random((2, 2))
print(arr)

[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]


Для создания матрицы заданного размера, наполненной случайными числами из стандартного нормального распределения, используйте метод `numpy.random.random((x, y))`, передав размер в качестве аргумента.

In [ ]:
arr = np.random.randn(2, 2)
print(arr)

[[-0.46947439  0.54256004]
 [-0.46341769 -0.46572975]]


In [ ]:
## Операции над матрицами

Создадим два массива

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

Чтобы сложить два массива поэлементно, воспользуйтесь функцией `numpy.add(x, y)` или перегруженным оператором `+`

Чтобы сложить два массива поэлементно, воспользуйтесь функцией `numpy.add(x, y)` или перегруженным оператором `+`

In [ ]:
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
y

array([[5., 6.],
       [7., 8.]])

In [ ]:
print(np.add(x, y))
print(x + y)

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


Чтобы вычесть поэлементно один массив из другого, воспользуйтесь функцией `numpy.subtract(x, y)` или перегруженным оператором `-`

In [ ]:
print(np.subtract(x, y))
print(x - y)

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


Чтобы перемножить два массива поэлементно, воспользуйтесь функцией `numpy.multiply(x, y)` или перегруженным оператором `*`

In [ ]:
print(np.multiply(x, y))
print(x * y)

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


Чтобы разделить поэлементно один массив на другой, воспользуйтесь функцией `numpy.divide(x, y)` или перегруженным оператором `/`

In [ ]:
print(np.divide(x, y))
print(x / y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Чтобы вычислить корень каждого элемента, воспользуйтесь функцией `numpy.sqrt(x)`

In [ ]:
print(x**2)

## Трансформация матриц

Создадим тестовую матрицу 4x4.

In [ ]:
x = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]])
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Чтобы транспонировать матрицу X, надо использовать метод `X.T` (сокращение от `X.transpose()`)

In [ ]:
print(x.T)

AttributeError: ignored

In [ ]:
x = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]])
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Чтобы изменить размерность матрицы X, например, с 3х4 на 2х6, надо использовать метод `X.reshape((2, 6))`.

In [ ]:
print(x.reshape((-1, 6)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Вектор в библиотеке NumPy имеет размерность `(3,)`, то есть 3 на ничто.

In [ ]:
vector = np.array([1, 2, 3])
print("vector.shape: {}".format(vector.shape))

vector.shape: (3,)


Многие библиотеки машинного обучения не понимают такую структуру, им нужен вектор размерностью `(3, 1)`. Функция `X.reshape((X.shape[0], 1))` помогает это сделать.

In [ ]:
new_vector = vector.reshape((-1, 1))
print("new_vector.shape: {}".format(new_vector.shape))

new_vector.shape: (3, 1)


Этот же метод можно использовать, чтобы превратить матрицу в одномерный массив.

In [ ]:
print(x.reshape((1, 12)))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


Однако для такой операции есть своя команда `X.flatten()`.

In [ ]:
print(x.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Умножение матриц и операции

Создадим матрицы 2x4, 4x3, 3x2 и два вектора 1x2.

In [ ]:
x = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]])
y = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]])
z = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

v = np.array([9,10])
w = np.array([11, 12])

Чтобы умножить матрицу А на матрицу В, воспользуйтесь функцией `numpy.dot(A, B)` или `A.dot(B)`.

При умножении матрицы 2x4 на матрицу 4x3 получится матрица размерностью 2x3.

In [ ]:
print(x.dot(y))
print(np.dot(x, y))
print("np.dot(x, y).shape: {}".format(np.dot(x, y).shape))

[[ 70  80  90]
 [158 184 210]]
[[ 70  80  90]
 [158 184 210]]
np.dot(x, y).shape: (2, 3)


Стоит заметить, что эта функция автоматически транспонирует векторы. Умножение матриц 3x2 и 1x2 невозможно, но `numpy.dot()` транспонирует вектор и производит умножение матриц 3x2 и 2x1.

In [ ]:
print(z.dot(v))
print(np.dot(z, v))

[ 29  67 105]
[ 29  67 105]


В частном случае это работает для произведения векторов.

In [ ]:
print(v.dot(w))
print(np.dot(v, w))

219
219


Создадим для примеров простейшую матрицу 2x2.

In [ ]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

Чтобы сложить все её элементы, воспользуемся функцией `numpy.sum(x)`.

In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
print(np.sum(x))

10


Чтобы сложить элементы столбцов, добавьте параметр `axis=0`.

In [ ]:
print(np.sum(x, axis=0))

[4 6]


Чтобы сложить элементы строк, добавьте параметр `axis=1`.

In [ ]:
print(np.sum(x, axis=1))

[3 7]


NumPy использует такую логику - если складываем элементы столбцов, значит проходим по строкам, значит идём по первому индексу (0, так как нумерация в программировании начинается с нуля), значит `axis=0`. Если складываем все элементы строки, значит идём по столбцам, по второму индексу, значит `axis=1`.

## Broadcasting

Создадим массив троек размером 2x3

In [ ]:
x = np.full((2, 3), 3)
print(x)

[[3 3 3]
 [3 3 3]]


При операциях со скалярами происходит операция с каждым элементом.

In [ ]:
print(x + 1)

[[4 4 4]
 [4 4 4]]


In [ ]:
print(x - 2)

[[1 1 1]
 [1 1 1]]


In [ ]:
print(x * 2)

[[6 6 6]
 [6 6 6]]


In [ ]:
print(x / 2)

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]]


In [ ]:
print(x ** 2)

[[9 9 9]
 [9 9 9]]


Пример того, как broadcasting может наказать за ошибки.

In [ ]:
y = np.full((1, 4), 4)
z = np.full((4, 1), 5)
print(y)
print(z)

[[4 4 4 4]]
[[5]
 [5]
 [5]
 [5]]


In [ ]:
print(y + z)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
